name: basketball_db
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - kaggle
  - isort
  - lxml
  - html5lib
  - python-dotenv
  - ipython-sql
  - jupyterlab-system-monitor
  - pip
  - pip:
     - nba_api
     - swifter[groupby]